<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="0" ignored="0" total="8" passed="8">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="133" started-at="2018-06-26T07:52:07Z" finished-at="2018-06-26T07:52:07Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="133" started-at="2018-06-26T07:52:07Z" finished-at="2018-06-26T07:52:07Z">
      <class name="TestSnl">
        <test-method status="PASS" signature="TestSnl1()[pri:0, instance:TestSnl@7c0e2abd]" name="TestSnl1" is-config="true" duration-ms="19" started-at="2018-06-26T13:22:07Z" finished-at="2018-06-26T13:22:07Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TestSnl1 -->
        <test-method status="PASS" signature="DeleteUnregisteredPlayer()[pri:0, instance:TestSnl@7c0e2abd]" name="DeleteUnregisteredPlayer" duration-ms="4" started-at="2018-06-26T13:22:07Z" finished-at="2018-06-26T13:22:07Z">
          <exception class="com.qainfotech.tap.training.snl.api.NoUserWithSuchUUIDException">
            <message>
              <![CDATA[No Player with uuid '988ed212-3234-4522-935d-a15b8916d068' on board]]>
            </message>
            <full-stacktrace>
              <![CDATA[com.qainfotech.tap.training.snl.api.NoUserWithSuchUUIDException: No Player with uuid '988ed212-3234-4522-935d-a15b8916d068' on board
	at com.qainfotech.tap.training.snl.api.Board.deletePlayer(Board.java:107)
	at TestSnl.DeleteUnregisteredPlayer(TestSnl.java:68)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- com.qainfotech.tap.training.snl.api.NoUserWithSuchUUIDException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- DeleteUnregisteredPlayer -->
        <test-method status="PASS" signature="TestSnl1()[pri:0, instance:TestSnl@7c0e2abd]" name="TestSnl1" is-config="true" duration-ms="3" started-at="2018-06-26T13:22:07Z" finished-at="2018-06-26T13:22:07Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TestSnl1 -->
        <test-method status="PASS" signature="GameInProgressException()[pri:0, instance:TestSnl@7c0e2abd]" name="GameInProgressException" duration-ms="6" started-at="2018-06-26T13:22:07Z" finished-at="2018-06-26T13:22:07Z">
          <exception class="com.qainfotech.tap.training.snl.api.GameInProgressException">
            <message>
              <![CDATA[New player cannot join since the game has started]]>
            </message>
            <full-stacktrace>
              <![CDATA[com.qainfotech.tap.training.snl.api.GameInProgressException: New player cannot join since the game has started
	at com.qainfotech.tap.training.snl.api.Board.registerPlayer(Board.java:72)
	at TestSnl.GameInProgressException(TestSnl.java:84)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- com.qainfotech.tap.training.snl.api.GameInProgressException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- GameInProgressException -->
        <test-method status="PASS" signature="TestSnl1()[pri:0, instance:TestSnl@7c0e2abd]" name="TestSnl1" is-config="true" duration-ms="3" started-at="2018-06-26T13:22:07Z" finished-at="2018-06-26T13:22:07Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TestSnl1 -->
        <test-method status="PASS" signature="checkThatTurnIsChanging()[pri:0, instance:TestSnl@7c0e2abd]" name="checkThatTurnIsChanging" duration-ms="6" started-at="2018-06-26T13:22:07Z" finished-at="2018-06-26T13:22:07Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkThatTurnIsChanging -->
        <test-method status="PASS" signature="TestSnl1()[pri:0, instance:TestSnl@7c0e2abd]" name="TestSnl1" is-config="true" duration-ms="1" started-at="2018-06-26T13:22:07Z" finished-at="2018-06-26T13:22:07Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TestSnl1 -->
        <test-method status="PASS" signature="deleteRegisteredPlayer()[pri:0, instance:TestSnl@7c0e2abd]" name="deleteRegisteredPlayer" duration-ms="6" started-at="2018-06-26T13:22:07Z" finished-at="2018-06-26T13:22:07Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- deleteRegisteredPlayer -->
        <test-method status="PASS" signature="TestSnl1()[pri:0, instance:TestSnl@7c0e2abd]" name="TestSnl1" is-config="true" duration-ms="4" started-at="2018-06-26T13:22:07Z" finished-at="2018-06-26T13:22:07Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TestSnl1 -->
        <test-method status="PASS" signature="playerIsAlreadyRegisterd()[pri:0, instance:TestSnl@7c0e2abd]" name="playerIsAlreadyRegisterd" duration-ms="3" started-at="2018-06-26T13:22:07Z" finished-at="2018-06-26T13:22:07Z">
          <exception class="com.qainfotech.tap.training.snl.api.PlayerExistsException">
            <message>
              <![CDATA[Player 'PRince' already exists on board]]>
            </message>
            <full-stacktrace>
              <![CDATA[com.qainfotech.tap.training.snl.api.PlayerExistsException: Player 'PRince' already exists on board
	at com.qainfotech.tap.training.snl.api.Board.registerPlayer(Board.java:69)
	at TestSnl.playerIsAlreadyRegisterd(TestSnl.java:37)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- com.qainfotech.tap.training.snl.api.PlayerExistsException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- playerIsAlreadyRegisterd -->
        <test-method status="PASS" signature="TestSnl1()[pri:0, instance:TestSnl@7c0e2abd]" name="TestSnl1" is-config="true" duration-ms="2" started-at="2018-06-26T13:22:07Z" finished-at="2018-06-26T13:22:07Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TestSnl1 -->
        <test-method status="PASS" signature="test_Invalid_turn()[pri:0, instance:TestSnl@7c0e2abd]" name="test_Invalid_turn" duration-ms="6" started-at="2018-06-26T13:22:07Z" finished-at="2018-06-26T13:22:07Z">
          <exception class="com.qainfotech.tap.training.snl.api.InvalidTurnException">
            <message>
              <![CDATA[Player 'e940eefc-82d7-4cf4-8cc8-45253a77e938' does not have the turn]]>
            </message>
            <full-stacktrace>
              <![CDATA[com.qainfotech.tap.training.snl.api.InvalidTurnException: Player 'e940eefc-82d7-4cf4-8cc8-45253a77e938' does not have the turn
	at com.qainfotech.tap.training.snl.api.Board.rollDice(Board.java:166)
	at TestSnl.test_Invalid_turn(TestSnl.java:97)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- com.qainfotech.tap.training.snl.api.InvalidTurnException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test_Invalid_turn -->
        <test-method status="PASS" signature="TestSnl1()[pri:0, instance:TestSnl@7c0e2abd]" name="TestSnl1" is-config="true" duration-ms="1" started-at="2018-06-26T13:22:07Z" finished-at="2018-06-26T13:22:07Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TestSnl1 -->
        <test-method status="PASS" signature="test_position_chnaged_or_not()[pri:0, instance:TestSnl@7c0e2abd]" name="test_position_chnaged_or_not" duration-ms="10" started-at="2018-06-26T13:22:07Z" finished-at="2018-06-26T13:22:07Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test_position_chnaged_or_not -->
        <test-method status="PASS" signature="TestSnl1()[pri:0, instance:TestSnl@7c0e2abd]" name="TestSnl1" is-config="true" duration-ms="3" started-at="2018-06-26T13:22:07Z" finished-at="2018-06-26T13:22:07Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TestSnl1 -->
        <test-method status="PASS" signature="addMaxPlayers()[pri:1, instance:TestSnl@7c0e2abd]" name="addMaxPlayers" duration-ms="9" started-at="2018-06-26T13:22:07Z" finished-at="2018-06-26T13:22:07Z">
          <exception class="com.qainfotech.tap.training.snl.api.MaxPlayersReachedExeption">
            <message>
              <![CDATA[The board already has maximum allowed Player: 4]]>
            </message>
            <full-stacktrace>
              <![CDATA[com.qainfotech.tap.training.snl.api.MaxPlayersReachedExeption: The board already has maximum allowed Player: 4
	at com.qainfotech.tap.training.snl.api.Board.registerPlayer(Board.java:64)
	at TestSnl.addMaxPlayers(TestSnl.java:47)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- com.qainfotech.tap.training.snl.api.MaxPlayersReachedExeption -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- addMaxPlayers -->
      </class> <!-- TestSnl -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
